### ISSUE TITLE
location of repo with code ? 

### ISSUE THREAD

**Issue by c1505** [redhat-developer-demos/knative-tutorial-module-advanced#3]
For this tutorial, it looks like one should clone a repo and there is some code in there that is needed in order to complete it.  It doesn't appear to be in these docs.  Looking specificially for this part `$TUTORIAL_HOME/bin/kafka-list-topics.sh` from this page https://redhat-developer-demos.github.io/knative-tutorial/knative-tutorial-adv/eventing-with-kafka.html#kn-eventing-kafka-source-to-sink .

**Comment by kameshsampath** [comment]
@c1505  - this a sub module of https://dn.dev/knative-tutorial, The instructions are available there. This module needs to be used with a flow as it has some dependencies.
